#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
