#!/usr/bin/env bash
#This script loops through 1-10 with while and if else statements

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
	echo "bad luck"
    elif [ $count -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi

    count=$((count+1))
done
