#!/usr/bin/env bash
# A script that prints 1-20 with various numeric luck thresholds
count=1

while [ $count -le 20 ]
do
    case $count in
        4)
	    echo "4"
            echo "bad luck from China"
	    ;;
	9)
	    echo "9"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "17"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $count
	    ;;
    esac

    count=$((count+1))
done
